name: Flutter Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events on all branches
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: flutter analyze
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up repository
      uses: actions/checkout@v2
    - name: Setup flutter action
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter analyze